### ISSUE TITLE
Expose all DB Pool Parameters

### ISSUE THREAD

**Issue by andrew-edgar** [cloudfoundry/bbs#15]
Right now there is only 1 parameter for Max Database Connections that is set the same to MaxActive  and MaxIdle.  We would like to be able to set these as possibly different values.

There should be the ability to set any DB Pool parameter in the config / manifest.

Can you please expose seperate properties at least for MaxActive and MaxIdle.

Thanks,

Andrew Edgar

**Comment by fraenkel** [comment]
The MaxConnLifetime would either need to be set to a reasonable value or exposed as well otherwise connections are reused forever.

**Comment by ematpl** [comment]
Thanks, @andrew-edgar. I see three methods on [database/sql.DB](https://golang.org/pkg/database/sql/#DB) that look applicable: [SetConnMaxLifetime](https://golang.org/pkg/database/sql/#DB.SetConnMaxLifetime), [SetMaxIdleConns](https://golang.org/pkg/database/sql/#DB.SetMaxIdleConns), and [SetMaxOpenConns](https://golang.org/pkg/database/sql/#DB.SetMaxOpenConns). Are there other tuning parameters you had in mind as "DB Pool parameters"?

@fraenkel, do you have suggestions for a reasonable value for the connection lifetime? What are the ramifications of allowing it to be reused it forever?

**Comment by fraenkel** [comment]
Read the reason why it was added in the first place.
https://github.com/golang/go/issues/9851
Like most things in the world, they aren't forever.

**Comment by ematpl** [comment]
Thanks for the context, @fraenkel.

@anoop2811 and @caod123, this connection-lifetime discussion may be relevant for your work on https://www.pivotaltracker.com/story/show/136754283.

**Comment by anoop2811** [comment]
Thanks @ematpl will look into those!

**Comment by ematpl** [comment]
Closing, as #16 is merged.
