### ISSUE TITLE
Docs: Broken link for structure of a TaskResponse

### ISSUE THREAD

**Issue by aashah** [cloudfoundry/bbs#19]
The section for [`CompletionCallbackUrl`](https://github.com/cloudfoundry/bbs/blob/master/doc/defining-tasks.md#completioncallbackurl-optional) contains a link describing what the response body for a `TaskResponse` looks like (currently pointing to `https://github.com/cloudfoundry/bbs/blob/master/doc/defining-tasks.md#retrieving-tasks`). This link seems broken.

**Comment by aashah** [comment]
Bunch of other links were broken as well, such as the one found in the [`EgressRules`](https://github.com/cloudfoundry/bbs/blob/master/doc/defining-tasks.md#egressrules-optional) section.

**Comment by ematpl** [comment]
Thanks, @aashah, we'll take a pass through the links in the BBS API docs and make sure they all resolve correctly. If you see any obvious corrections in the meantime, we'd welcome a PR!

Best,
Eric

**Comment by ematpl** [comment]
Closing with https://github.com/cloudfoundry/diego-release/commit/c924d3e46484ae5b025178f5aa87ccb19959f0a3.
