### ISSUE TITLE
Request to log the request which caused the maximum latency in past notify interval

### ISSUE THREAD

**Issue by devtdeng** [cloudfoundry/bbs#33]
Reasons for this request:

1. Currently not all requests' starting/tasks.completed event are recorded in logs.
2. When some latency triggers KPI's alert, it's difficult to identify which request causes the latency. 

Changes:
In request_stat_metron_notifier.go, add param/return value to functions UpdateLatency and ReadAndResetLatency for request.

**Comment by jvshahid** [comment]
@devtdeng would this feature https://www.pivotaltracker.com/story/show/120552215 gives you what you need. This feature is trying to make use of a recent loggregator change to allow metadata along the emitted metrics. For example, the bbs would emit a latency metric per endpoint and that extra tag on the metric can be used to determine which endpoint caused the overall latency metric to go above the configured threshold in the data aggregation service.

**Comment by devtdeng** [comment]
@jvshahid that's great if we can identify which request/endpoint caused the maximum latency with the metric.

**Comment by devtdeng** [comment]
@jvshahid 
Are there any progress on this one?

**Comment by jvshahid** [comment]
@devtdeng I'm not on the team anymore.  I suggest using @cloudfoundry/cf-diego in the future, which will ping the current engineers on the team.

**Comment by sunjayBhatia** [comment]
@devtdeng we have not made progress on this yet, but I pulled the story mentioned above higher up in priority to see if we can shape it up and get something worked out

**Comment by heyjcollins** [comment]
As this item has been open for quite a long time, I'm going to go ahead and close it.
