### ISSUE TITLE
image_layer.proto not valid when compiled to Ruby (for Cloud Controller)

### ISSUE THREAD

**Issue by charleshansen** [cloudfoundry/bbs#34]
Cloud Controller has not recompiled the BBS protos in some time, and when I attempted to do so, the ruby client library was invalid.

The [image_layer.proto](https://github.com/cloudfoundry/bbs/blob/5a687f23ff3bc7ec3361bda4e129ab4c55976880/models/image_layer.proto) has some lower case enums in it and this leads to invalid Ruby. This is a [known issue](https://github.com/protocolbuffers/protobuf/issues/1965), but does not look like it will be fixed anytime soon. 

I think the only path forward is to replace all the proto enums with Capitalized versions.

The bug is ultimately in the ruby client generator. It is possible this would go away if BBS upgraded to proto3, since that is a different generator with better support.

**Comment by emalm** [comment]
Hey, @charleshansen, I'm a little confused with the reference to https://github.com/protocolbuffers/protobuf/issues/1965. Is this also an issue if you follow https://github.com/cloudfoundry/bbs#generating-ruby-models-for-bbs-models and use https://github.com/ruby-protobuf/protobuf? Or are the BBS's Ruby generation docs out of date?

/cc @jvshahid @tcdowney

**Comment by charleshansen** [comment]
I believe the issue was filed in protobuf as a way to fix bugs in ruby compilers in general. I actually used  the [capi wiki](https://github.com/cloudfoundry/cloud_controller_ng/wiki/Updating-our-ruby-protobuf-models-for-BBS) to compile the protos. This does differ slightly from the bbs docs, I can try those too. It is difficult to compile ruby in proto2 syntax unless you manually downgrade an unknown set of libraries, so no guarantees.

I also found https://github.com/ruby-protobuf/protobuf/issues/326, which indicates this issue has been fixed in ruby-protobuf, so there is some hope.

**Comment by jvshahid** [comment]
I tried to generate the .rb files using the method we documented in the README and got the following enum in `image_layer.pb.rb`:
```ruby
    class DigestAlgorithm < ::Protobuf::Enum
      define :DigestAlgorithmInvalid, 0
      define :sha256, 1
      define :sha512, 2
    end
```

when I tried loading the image_layer enum in an irb session I got the following:
```
NameError: wrong constant name sha256
        from /home/jvshahid/.rvm/gems/ruby-2.2.3/gems/protobuf-3.8.4/lib/protobuf/enum.rb:60:in `const_set'
        from /home/jvshahid/.rvm/gems/ruby-2.2.3/gems/protobuf-3.8.4/lib/protobuf/enum.rb:60:in `define'
        from /tmp/ruby-proto/image_layer.pb.rb:23:in `<class:DigestAlgorithm>'
        from /tmp/ruby-proto/image_layer.pb.rb:21:in `<class:ImageLayer>'
        from /tmp/ruby-proto/image_layer.pb.rb:20:in `<module:Models>'
        from /tmp/ruby-proto/image_layer.pb.rb:14:in `<top (required)>'
        from /home/jvshahid/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:121:in `require'
        from /home/jvshahid/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:121:in `require'
        from (irb):2
        from /home/jvshahid/.rvm/rubies/ruby-2.2.3/bin/irb:11:in `<main>'
```

**Comment by jvshahid** [comment]
do be fair, the [protobuf style guide](https://developers.google.com/protocol-buffers/docs/style#enums) mention that enum constants should be `CAPITAL_WITH_UNDERSCORES`. I played around with changing the enum values to start with upper case and I think this can work, except that it breaks json serialization. @emalm do you feel strongly about the json serialization ?

**Comment by jvshahid** [comment]
alternatively, we can add to the docs that the env variable `PB_UPCASE_ENUMS` need to be set in order to guarantee valid ruby protobufs. The only concern in this case is that all enum values will be upper case which will break other code, for example code that use Task's `State` enum values. They will change from `Pending` to `PENDING`

**Comment by emalm** [comment]
@jvshahid Sure, I'd be fine with changing the JSON serialization to have title- or upper-case renderings of the enum values. I vaguely recall discussion during https://www.pivotaltracker.com/story/show/158948633 when we initially thought that would be difficult for other reasons &ndash; maybe Golang capitalization conventions?

@charleshansen @tcdowney would setting the `PB_UPCASE_ENUMS` env var during Ruby code generation be of interest to you?

**Comment by charleshansen** [comment]
I think it would be alright to use PB_UPCASE_ENUMS (as long as we update the docs). I believe that state always should be all caps when presented to the user anyway, so it wouldn't be a big deal to change it. It is possible some CAPI code will have to change to accommodate this but I don't expect it to be expensive.

I still have a minor preference to make the change in BBS just to follow the styleguide and to avoid special-casing our compile process, but otherwise both options are fine by me.

**Comment by emalm** [comment]
Discussed further with @jvshahid and the rest of the Diego team, and we're planning to switch these enums to UPPER_CASE to match the [Protobuf style guide for enums](https://developers.google.com/protocol-buffers/docs/style#enums):

> Use... CAPITALS_WITH_UNDERSCORES for value names.
