### ISSUE TITLE
desired_lrps.run_info too small when using MySQL as BBS db backend

### ISSUE THREAD

**Issue by JamesClonk** [cloudfoundry/bbs#9]
We've recently switched from `etcd` to `mysql` on our bbs backend, and noticed that it is not possible anymore to run apps on Diego if they have a lot of service bindings and started experience various app restage / push failures.

Tracking down the problem we found out that the table column `desired_lrps.run_info` is too small on MySQL.
The migration runs the create table statement for desired_lrps regardless of DB with 
```
run_info TEXT NOT NULL
```
, which on PostgreSQL translates to (almost) unlimited length, but only 65,535 characters on MySQL! 😨 
This can easily be filled with apps that have a lot of service bindings for example.

Example output from bbs logfile:
```
{"timestamp":"1470924426.977551937","source":"bbs","message":"bbs.desired-lrp-handler.desire-lrp.failed-inserting-desired","log_level":2,"data":{"error":"Error 1406: Data too long for column 'run_info' at row 1","process_guid":"ad86073d-a2fb-482f-832b-d3ae5b7834b0-f62a8b72-8190-495a-b653-c2ae5f554d0b","session":"7.62920"}}
```
diego-release used: 0.1481.0

A possible solution for this problem could be to use different table create statements for PostgreSQL and MySQL, with at least using `MEDIUMTEXT` as column type for `run_info`.
Or running an additional migration afterwards (if db==mysql) with an `ALTER TABLE desired_lrps MODIFY COLUMN run_info MEDIUMTEXT NOT NULL;` or similar.

**Comment by ematpl** [comment]
Closing, as this is fixed in [Diego v0.1483.0](https://github.com/cloudfoundry/diego-release/releases/tag/v0.1483.0).

Best,
Eric
